// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL3BviCZfaK9DMrWUpmqAX3cs5OtF50FU',
    appId: '1:455984127761:web:8c82ea3ced7acf85db36b0',
    messagingSenderId: '455984127761',
    projectId: 'shoppixa-d0298',
    authDomain: 'shoppixa-d0298.firebaseapp.com',
    storageBucket: 'shoppixa-d0298.appspot.com',
    measurementId: 'G-6XWKZDSY6T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTXdFO4Rd_f-gT_YjZa1npQZiiwiRwztE',
    appId: '1:455984127761:android:cd0f964b48cad449db36b0',
    messagingSenderId: '455984127761',
    projectId: 'shoppixa-d0298',
    storageBucket: 'shoppixa-d0298.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSKMuDGKVETQgDBe7U6b5iTX9-ciAhBow',
    appId: '1:455984127761:ios:71a499077941318ddb36b0',
    messagingSenderId: '455984127761',
    projectId: 'shoppixa-d0298',
    storageBucket: 'shoppixa-d0298.appspot.com',
    iosBundleId: 'com.shoppixa.shoppixa',
  );
}
